version: "3"
services:
  node:
    build:
      context: back
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes: 
      - ./back:/var/www/backend/
      - /var/www/backend/node_modules
    environment:
      WAIT_HOSTS: db:27017

  front:
    build:
      context: front
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./front:/var/www/frontend
      - /var/www/frontend/node_modules
    links:
      - node

  db:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017